### ISSUE TITLE
Umanager does not handle usernames containing a dot

### ISSUE THREAD

**Issue by napalm5** [lcm-unimi/userconf#13]
Both when creating and renewing an account, if the username contains a dot, the program returns error "Invalid character".
This is not really a problem when creating a new account, but it means that usernames containing a dot cannot be renewed by umanager.

**Comment by andreatsh** [comment]
Usernames with dots are no longer supported for LCM cluster for different reasons.
This is not a bug, but it's a design choice made by the team at the beginning of the project.
