### ISSUE TITLE
.forward file ownership

### ISSUE THREAD

**Issue by savaroskij** [lcm-unimi/userconf#14]
File .forward is created by userGUI.py with the ownership of the user that launches umanager (for other reasons this user is always root). As a result, users cannot modify their own .forward file (however they can delete and recreate it).

```
# Configure user's mail
        mforwardfile="/home/"+self.username.value+"/.forward"
        ofs = open(mforwardfile,"w")
        ofs.write(self.username.value)
        ofs.write("\n")
        ofs.write(self.email.value)
ofs.close()
```

Possible solution?:
```
import grp
import os
[...]
gid = grp.getgrnam("users").gr_gid
os.chown(mforwardfile, useruidNo, gid)
[...]
```

Is this a bug? Or something wanted?

**Comment by andreatsh** [comment]
The users' _.forward_ file should be created by the **useradd** command with the right owner and permissions. Then the snippet of code, that you correctly posted, configure the file. 

Please check if the file _/etc/skel/.forward_ exist on your master server. If not, create the file and then try to add a new user with umanager, this should solve the issue.

Btw this is an unwanted behavior, so feel free to go ahead with your proposed fix.

**Comment by savaroskij** [comment]
Touching _/etc/skel/.forward_ fixed the issue.
Thanks for your support.
