### ISSUE TITLE
Nome dello script userconf

### ISSUE THREAD

**Issue by Sbozzolo** [lcm-unimi/userconf#4]
Lo script userconf si occupa della quasi totalita' delle operazioni sugli utenti del sistema, ma mi sembra che il suo nome non rispecchi questa sua funzione. 

Potrebbe essere utile cambiare il nome con un nome piu' esplicativo?

**Comment by LamaKing** [comment]
In effetti, fa ben più che configurare gli utenti. Mi verrebbe da dire che management sia il termine più corretto, anche se un po' lungo.
Qualcosa come user(s)ctl o user(s)mgmt?
O, volendo includere il fatto che è un interfaccia al database, userdbctl potrebbe essere un'idea.

**Comment by Sbozzolo** [comment]
Se io dovessi desrivere questo script con due parole userei users manager.

**Comment by andreatsh** [comment]
Proposta: usersmng?

**Comment by Sbozzolo** [comment]
Io preferisco i nomi prunciabili, quindi se devo abbreviare direi umanager
(che può anche essere letto come youmanager, che sembra il nome di un
periodico per aspiranti dirigenti).

**Comment by andreatsh** [comment]
Onesto. user(s)manager e` troppo lungo.
Per cui se nessun altro si esprime io voto umanager.

**Comment by LamaKing** [comment]
Mi piace il ragionamento, io pure voto umanager.

**Comment by andreatsh** [comment]
Change project name in umanager from v1.0
